[package]
name = "defs"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2018"

[dependencies]
raw-window-handle = "0.3.3"
cgmath = "0.18.0"
image = { version = "0.23.14", default-features = false, features = ["jpeg", "png"] }
winit = "0.25.0"
model = { path = "../model" }
