
[workspace]
members = [
    "model",
    "defs",
    "renderer",
    "engine",
    "platform_desktop",
    "scenegen",
    "examples/scenery",
    "examples/menu"
]
default-members = [
    "examples/scenery"
]
