[package]
name = "generated"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2021"

[build-dependencies]
model = { path = "../../model" }
collada = { path = "../../collada" }
scenegen = { path = "../../scenegen" }

[dependencies]
cgmath = "0.18.0"
defs = { path = "../../defs" }
platform_windows = { path = "../../platform_desktop" }
renderer = { path = "../../renderer" }
engine = { path = "../../engine" }
