[package]
name = "platform_windows"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.24.0"
raw-window-handle = "0.3.3"
engine = { path = "../engine" }
defs = { path = "../defs" }
