[package]
name = "collada"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde-xml-rs = "0.4.1"
toml = "0.5.8"
model = { path = "../model" }
