[package]
name = "renderer"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.32.1"
ash-window = "0.6.0"
raw-window-handle = "0.3.3"
vk-shader-macros = "0.2.6"
vk-mem = "0.2.2"
defs = { path = "../defs" }
