[package]
name = "scenegen"
version = "0.1.0"
authors = ["Thomas <thomasr1987@gmail.com>"]
edition = "2018"

[dependencies]
jsonschema = "0.12.1"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.68"

[dev-dependencies]
serial_test = "0.5.1"
